<div id="invoice-tax" data-invoice-tax="<?= count($this->order->getInvoice()[0]->getInvoice()->getServiceInvoiceTax()) > 0 ? $this->order->getInvoice()[0]->getInvoice()->getServiceInvoiceTax()[0]->getServiceInvoiceTax()->getId() : '' ?>">                
    <?php if ($this->defaultCompany && $this->userModel->getUserCompany() && $this->userModel->getUserCompany()->getId() === $this->defaultCompany->getId()) { ?>
    <?php if ($this->order->getInvoice()[0]->getInvoice()->getStatus()->getStatus() == 'waiting generate invoice') { ?>
        <form enctype="multipart/form-data">
            <input type="hidden" name="invoice" value="<?= $this->order->getInvoice()[0]->getInvoice()->getId() ?>">
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span><?= $this->translate('Select a carrier invoice XML') ?></span>        
                <input data-success-url="/<?= $this->module_name ?>/order/id/<?= $this->order->getId() ?>" data-url="/finance/add-service-invoice-tax.json" data-progress-bar=".progress .progress-bar" accept=".xml,.xmlx" class="fileupload" id="upload-nfe" type="file" name="NFE">
            </span>
            <div id="progress" class="progress">
                <div class="progress-bar progress-bar-success"></div>
            </div>
        </form>
    <?php } ?> 
    <?php } ?> 
    <?php if (count($this->order->getInvoice()[0]->getInvoice()->getServiceInvoiceTax()) > 0) { ?>
        <iframe src="/vendor/pdf.js/web/viewer.html?zoom=page-width&file=/finance/service-invoice-tax/id/<?= $this->order->getInvoice()[0]->getInvoice()->getServiceInvoiceTax()[0]->getServiceInvoiceTax()->getInvoiceNumber() ?>.pdf" class="pdf-container"></iframe> 
    <?php } ?> 
</div>